name: Testing
on: [pull_request]

jobs:
  cpptests:
    name: C++ tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get -y -q install cmake gcc libeigen3-dev

      - name: Install Google Test
        run: |
            wget -qO - https://github.com/google/googletest/archive/release-1.8.1.tar.gz | tar -xz
            cmake -D CMAKE_INSTALL_PREFIX:PATH=$HOME/googletest -D CMAKE_BUILD_TYPE=Release googletest-release-1.8.1
            make install

      - name: Build and run unit tests
        run: |
            cd pennylane_lightning/src/tests
            GOOGLETEST_DIR=$HOME/googletest make test

  pythontests:
    name: Python tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:

      - name: Checkout PennyLane-Lightning
        uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: sudo apt-get -y -q install cmake gcc libeigen3-dev

      - name: Get required Python packages
        run: |
          pip install numpy pybind11 pytest pytest-cov flaky

      - name: Install lightning.qubit device
        run: |
          cd main
          pip install -e .

      - name: Checkout PennyLane
        uses: actions/checkout@v2
        with:
          repository: PennyLaneAI/pennylane
          path: pl

      - name: Install PennyLane
        run: |
          cd pl
          pip install -e .

      - name: Run PennyLane-Lightning unit tests
        run: |
          cd main/
          pytest tests/ --cov=pennylane_lightning --cov-report term-missing --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          file: main/coverage.xml

      - name: Run PennyLane shared test suite
        run: |
          cd pl
          pytest pennylane/devices/tests --device lightning.qubit --analytic False --skip-ops --shots=20000
          pytest pennylane/devices/tests --device lightning.qubit --analytic True --skip-ops
