name: Compat Check Docker - Lightning@master

on:
  schedule:
    - cron: "0 4 * * 1-5"  # Run daily at 4am Mon-Fri
  workflow_dispatch:

concurrency:
  group: docker_linux_x86_64-master
  cancel-in-progress: true

jobs:
  docker_linux_x86_64_develop:
    name: Docker develop - Linux::x86_64
    uses: ./.github/workflows/docker_linux_x86_64.yml
    with:
      lightning-version: master
      pennylane-version: master
      push-to-dockerhub: false
    secrets: inherit # pass all secrets
